# Generated by Django 3.1 on 2020-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fluxo',
            fields=[
                ('cod_pes', models.IntegerField(primary_key=True, serialize=False)),
                ('sent_pes', models.BooleanField()),
                ('time_pes', models.TimeField()),
            ],
        ),
    ]
